name: push to dockerhub
on: 
  push:
      branch: 
      -main

jobs:
  build:
    -
      name: Checkout
      uses: actions/checkout@v4

    -
      name: Setup docker
      uses: docker/setup-buildx-action@v3
    - name: Build docker image
      run: docker build -f apps/web-docker/Dockerfile -t web-docker:${{ github.sha }} .
      


     